"""
Serializers (tasks/serializers.py)
====================================
A Serializer is the DRF equivalent of a Django Form, but for APIs.

It does two things:
  1. SERIALIZATION:   Python object → JSON  (for API responses)
  2. DESERIALIZATION: JSON → Python object  (for API requests)

Just like ModelForm maps to a Model, ModelSerializer maps to a Model too.
"""

from rest_framework import serializers
from .models import Task


class TaskSerializer(serializers.ModelSerializer):
    """
    Converts Task model instances to/from JSON.
    
    Example output:
    {
        "id": 1,
        "title": "Buy groceries",
        "description": "Milk, eggs, bread",
        "completed": false,
        "created_at": "2024-01-15T10:30:00Z",
        "updated_at": "2024-01-15T10:30:00Z"
    }
    """

    # read_only_fields: these fields appear in responses
    # but cannot be set by the user in POST/PUT requests
    # - 'id' is auto-generated by the database
    # - 'created_at' is auto-set when task is created
    # - 'updated_at' is auto-set every time the task is saved

    class Meta:
        model = Task  # Which model to serialize
        fields = [
            'id',
            'title',
            'description',
            'completed',
            'created_at',
            'updated_at',
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']
        # 'user' is intentionally excluded:
        #   - We don't want users to manually set the owner
        #   - The view sets user=request.user when saving

    def validate_title(self, value):
        """
        Custom validation for the title field.
        validate_<fieldname> methods run automatically.
        """
        value = value.strip()
        if len(value) < 3:
            raise serializers.ValidationError(
                "Title must be at least 3 characters long."
            )
        return value
